version: '3.9'

services:
  notify:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8002:8002"
    environment:
      - AMQP_CONN=amqp://guest:guest@host.docker.internal:5672/
